# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters


colorScheme = "Fire"
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = false


[header]
  layout = "fixed-fill-blur" # valid options: basic, fixed, fixed-fill, fixed-fill-blur

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "page" # valid options: page, profile, hero, card, background, custom
  homepageImage = "img/clown.png" # used in: hero, and card
  showRecent = true

[article]
  showDate = true
  showComments = false
  showReadingTime = false
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = false
  showSummary = true
  
[list]
  showBreadcrumbs = false
  showSummary = true
  groupByYear = false

[sitemap]

[taxonomy]


[term]


[firebase]


[fathomAnalytics]


[buymeacoffee]

[verification]

